server:
  port: 8080
  servlet:
    session:
      timeout: 30m

spring:
  application:
    name: AITravelPlanner
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    com.travelplanner: DEBUG

api:
  keys:
    #TODO  填入相关api值
    xfyun-app-id: ${XFYUN_APP_ID:} # 请配置讯飞语音识别App ID
    xfyun-api-key: ${XFYUN_API_KEY:} # 请配置讯飞语音识别API Key
    xfyun-api-secret: ${XFYUN_API_SECRET:} # 请配置讯飞语音识别API Secret
    #高德地图API
    amap-key: ${AMAP_KEY:} # 请配置高德地图API Key
    llm-api-key: ${LLM_API_KEY:} # 请配置大语言模型API Key
    llm-api-secret: ${LLM_API_SECRET:} # 请配置大语言模型API Secret
    llm-app-id: ${LLM_APP_ID:} # 请配置大语言模型App ID